import subprocess

cmd_str = r"java -jar rars1_6.jar dump .text BinaryText premade.txt input2.txt"
cmd_args = cmd_str.split()
subprocess.run(cmd_args)

cmd_str = r"python main.py"
cmd_args = cmd_str.split()
subprocess.run(cmd_args)

# output.txt is generated by our code
with open("premade.txt") as premade, open("output.txt") as ours:
    premade_lines = premade.readlines()
    our_lines = ours.readlines()

for premade_line, our_line in zip(premade_lines, our_lines):
    our_line = "".join( our_line.split() )
    premade_line = "".join( premade_line.split() )

    if premade_line != our_line:
        print("Doesn't match")
        print("Premade: ", premade_line)
        print("Ours: ", our_line)
        break


print("Valid!")